#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Sensor, S4,     ,               sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Motor,  motorA,           ,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,           ,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int ot=0;
int cikl=0;
task main()
{
	resetMotorEncoder(motorA);
	resetMotorEncoder(motorD);
	motor[motorA]=50;
	motor[motorD]=50;
	sleep(4500);
	motor[motorA]=0;
	motor[motorD]=0;
	sleep(500);
	while(true)
	{
		ot = SensorValue[S4];
		if(cikl>13000)
		{
			break;
		}
		else
		{
			if(ot>640)
			{
				motor[motorA]=50;
				motor[motorD]=0;
				sleep(1);
			}
			else
			{
				motor[motorD]=50;
				motor[motorA]=0;
				sleep(1);
			}
		}
		cikl=cikl+1;
	}
	motor[motorA]=50;
	motor[motorD]=50;
	sleep(1000);

	motor[motorA]=50;
	motor[motorD]=-50;
	sleep(550);

	motor[motorA]=50;
	motor[motorD]=50;
	sleep(3800);

	motor[motorA]=50;
	motor[motorD]=-50;
	sleep(1100);

	motor[motorA]=50;
	motor[motorD]=50;
	sleep(3000);
ot=0;
cikl=0;
while(true)
	{
		ot = SensorValue[S4];
		if(cikl>13000)
		{
			break;
		}
		else
		{
			if(ot>640)
			{
				motor[motorA]=50;
				motor[motorD]=0;
				sleep(1);
			}
			else
			{
				motor[motorD]=50;
				motor[motorA]=0;
				sleep(1);
			}
		}
		cikl=cikl+1;
	}

	motor[motorA]=50;
	motor[motorD]=50;
	sleep(1000);


	motor[motorA]=-50;
	motor[motorD]=50;
	sleep(550);

	motor[motorA]=50;
	motor[motorD]=50;
	sleep(5500);






















































































































}
